version: '3'

services:
  server:
    container_name: dq-server
    build: ./../app
    ports:
      - "${DQ_TCP_HOST}:${DQ_TCP_PORT}:12000"
    volumes:
      - ./logs/dq:/dq/logs
    environment:
      - TZ=${TZ}
      - DQ_PROFILER_ENABLED=${DQ_PROFILER_ENABLED}
      - DQ_INACTIVE_CONNECTION_TIME_SECONDS=${DQ_INACTIVE_CONNECTION_TIME_SECONDS}